name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.0.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.10.0

        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Start LocalStack
        run: docker-compose up -d
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

      - name: Terraform Config
        run: |
          cd terraform
          bash run-tflocal.sh

      - name: Run tests
        run: ./gradlew test